version: 1.1.0-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build_script:
- cmd: .\build.cmd All
test:
  assemblies: 'Source\**\*.Specs.dll'
deploy: off
artifacts:
- path: artifacts\nuget\*
  name: nuget
